name = "JuliaWorkshop"
uuid = "9f73e154-e032-11ed-1bae-81cc86e26d0a"
authors = ["Maximilian S. Ernst, Moritz Ketzer, Aaron Peikert and contributors"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]